ROOT_DIR=$(shell git rev-parse --show-toplevel)
TOOLS_DIR=$(ROOT_DIR)/.tools
GUESTBOOK := $(ROOT_DIR)/bin/guestbook
COMPOSE_FILE := $(ROOT_DIR)/monitoring-lgtm/podman-compose.yaml

# Returns all .go-files
ALL_GO_FILES=$(shell find $(ROOT_DIR) -type f -name "*.go")

# Set tool-paths for easier access
LINT := $(TOOLS_DIR)/golangci-lint

# Env vars
GO_ENV=$(shell CGO_ENABLED=0)

# Versioning
GO_VERSION=1.22
GOLINT_VERSION=v1.57.2


